### ISSUE TITLE
The game crashes while using the camera stick during gameplay

### ISSUE THREAD

**Issue by takuminightcore** [GrimMaple/JuicedFixes#8]
While trying to perform a race I tried to pan the camera during the race and when I move it to either side the game crashes and you immediately lose the race or even worse lose pink slips and bets.

**Comment by Fruit911** [comment]
he probably not gona fix it...

**Comment by wefalltomorrow** [comment]
No point anyways, this doesn't fix anything that can't be fixed with other mods.

**Comment by Fruit911** [comment]
> No point anyways, this doesn't fix anything that can't be fixed with other mods.

? makes no sense.. its fixable just unbind the look left option..

**Comment by Fruit911** [comment]
but im no coder so i cant do it..

**Comment by wefalltomorrow** [comment]
> > No point anyways, this doesn't fix anything that can't be fixed with other mods.
> 
> ? makes no sense.. its fixable just unbind the look left option..

I'm not talking about this PR, I'm talking about JuicedFixes itself. It's redundant, just get what you need off the Juiced page on PCGamingWiki

**Comment by Fruit911** [comment]
> > > No point anyways, this doesn't fix anything that can't be fixed with other mods.
> > 
> > 
> > ? makes no sense.. its fixable just unbind the look left option..
> 
> I'm not talking about this PR, I'm talking about JuicedFixes itself. It's redundant, just get what you need off the Juiced page on PCGamingWiki

so there i find a fix for that crashing when using the right stick?

**Comment by wefalltomorrow** [comment]
...no

You don't use JuicedFixes at all and you don't get a crash with the right stick.

**Comment by Fruit911** [comment]
yeah but how can i use a controller than ? with keyboard its undriveable..

**Comment by wefalltomorrow** [comment]
Dude... https://www.pcgamingwiki.com/wiki/Juiced

**Comment by Fruit911** [comment]
> Dude... https://www.pcgamingwiki.com/wiki/Juiced

okay got everything from the fixes... drives like a boat.. also with the steering fix.. @GrimMaple's fix is so much better from the steering.. sad

**Comment by Fruit911** [comment]
if someone might fix it ill gona donate him

**Comment by GrimMaple** [comment]
I think I actually fixed this in recent refactorings, but didn't make a release. I'll check that later and if it's fixed I'll draft a new release

**Comment by GrimMaple** [comment]
@Fruit911 I rechecked stuff. Yes, the crash is fixed in the new release. However, there are a few problems with it as well, so I'm gonna check those problems ASAP and make a new release out of it :)

**Comment by Fruit911** [comment]
> @Fruit911 I rechecked stuff. Yes, the crash is fixed in the new release. However, there are a few problems with it as well, so I'm gonna check those problems ASAP and make a new release out of it :)

Awesome to hear! Thanks! Let me know when u drop the Update :)

**Comment by Fruit911** [comment]
@GrimMaple any new Infos?

**Comment by GrimMaple** [comment]
> @GrimMaple any new Infos?

Done. The new release is on the release page. Also, here's a link for it: https://github.com/GrimMaple/JuicedFixes/releases/tag/v0.2
There are still issues, but the crashing should be fixed. At least I didn't experience crashing during testing.

Also, don't pause. Seriously, don't. It breaks everything xD
